# Generated by Django 5.0.6 on 2024-05-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
